""" pfadd_ui.py --

 UI generated by GUI Builder Build 146 on 2010-04-06 19:50:22 from:
    /media/data/hubi/code/python/pfgui3/src/pfadd.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Pfadd(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._frame_1 = Tkinter.Frame(root,
        )
        self._frame_2 = Tkinter.Frame(root,
        )
        self._txData = Tkinter.Text(root,
            height = 0,
            width = 30,
        )
        self._lsLinks = Tkinter.Listbox(root,
            height = 0,
            selectmode = "multiple",
            width = 30,
        )
        self._butScan = Tkinter.Button(self._frame_2,
            text = "scan for links",
        )
        self._butRemove = Tkinter.Button(self._frame_1,
            text = "remove selected link",
        )
        self._butAdd = Tkinter.Button(root,
            text = "add packet",
        )
        self._butClearall = Tkinter.Button(self._frame_1,
            text = "clear all links",
        )
        self._panedwindow_1 = Tkinter.PanedWindow(self._frame_1,
            height = 0,
            width = 0,
        )
        self._panedwindow_2 = Tkinter.PanedWindow(self._frame_2,
            height = 0,
            width = 0,
        )

        # widget commands

        self._txData.configure(
            xscrollcommand = self._txData_xscrollcommand
        )
        self._txData.configure(
            yscrollcommand = self._txData_yscrollcommand
        )
        self._lsLinks.configure(
            xscrollcommand = self._lsLinks_xscrollcommand
        )
        self._lsLinks.configure(
            yscrollcommand = self._lsLinks_yscrollcommand
        )
        self._butScan.configure(
            command = self._butScan_command
        )
        self._butRemove.configure(
            command = self._butRemove_command
        )
        self._butAdd.configure(
            command = self._butAdd_command
        )
        self._butClearall.configure(
            command = self._butClearall_command
        )


        # Geometry Management
        self._frame_1.grid(
            in_    = root,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_2.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._txData.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 5,
            pady = 5,
            rowspan = 1,
            sticky = "news"
        )
        self._lsLinks.grid(
            in_    = root,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 5,
            pady = 5,
            rowspan = 1,
            sticky = "news"
        )
        self._butScan.grid(
            in_    = self._frame_2,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._butRemove.grid(
            in_    = self._frame_1,
            column = 4,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._butAdd.grid(
            in_    = root,
            column = 2,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = "e"
        )
        self._butClearall.grid(
            in_    = self._frame_1,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._panedwindow_1.grid(
            in_    = self._frame_1,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._panedwindow_2.grid(
            in_    = self._frame_2,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 1, minsize = 178, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 58, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 24, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 2, pad = 0)
        root.grid_columnconfigure(2, weight = 1, minsize = 483, pad = 0)
        self._frame_1.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_1.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_1.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_1.grid_columnconfigure(3, weight = 0, minsize = 40, pad = 0)
        self._frame_1.grid_columnconfigure(4, weight = 0, minsize = 40, pad = 0)
        self._frame_2.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_2.grid_columnconfigure(1, weight = 1, minsize = 43, pad = 0)
        self._frame_2.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)


