""" pfmain_ui.py --

 UI generated by GUI Builder Build 146 on 2010-04-06 19:41:12 from:
    /media/data/hubi/code/python/pfgui3/pfmain.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Pfmain(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._frame_1 = Tkinter.Frame(root,
        )
        self._frame_2 = Tkinter.Frame(root,
        )
        self._frame_4 = Tkinter.Frame(root,
        )
        self._frame_5 = Tkinter.Frame(root,
        )
        self._labelframe_1 = Tkinter.LabelFrame(self._frame_1,
            text = "packet information",
        )
        self._labelframe_2 = Tkinter.LabelFrame(self._frame_1,
            text = "log",
        )
        self._frame_3 = Tkinter.Frame(self._frame_2,
        )
        self._frame_6 = Tkinter.Frame(self._frame_2,
        )
        self._txLog = Tkinter.Text(self._labelframe_2,
            height = 0,
            width = 33,
        )
        self._labStatus = Tkinter.Label(self._labelframe_1,
            anchor = "nw",
            justify = "left",
            text = "<packet info here>",
            wraplength = 230,
        )
        self._butAdd = Tkinter.Button(self._frame_3,
            text = "add packets",
        )
        self._butStart = Tkinter.Button(self._frame_3,
            text = "start dl+exr",
        )
        self._butExit = Tkinter.Button(self._frame_4,
            text = "exit",
        )
        self._panedwindow_1 = Tkinter.PanedWindow(self._frame_4,
            height = 0,
            width = 0,
        )
        self._butUpdate = Tkinter.Button(self._frame_3,
            text = "update list",
        )
        self._butHistory = Tkinter.Button(self._frame_3,
            text = "show history",
        )
        self._butPwd = Tkinter.Button(self._frame_3,
            text = "password editor",
        )
        self._butKill = Tkinter.Button(self._frame_4,
            text = "kill pfserver",
        )
        self._butShutdown = Tkinter.Button(self._frame_5,
            text = "shutdown nimmer",
        )
        self._panedwindow_2 = Tkinter.PanedWindow(self._frame_5,
            height = 0,
            width = 0,
        )
        self._lsPackets = Tkinter.Listbox(self._frame_6,
            activestyle = "dotbox",
            height = 18,
            width = 0,
        )
        self._sclPackets = Tkinter.Scrollbar(self._frame_6,
        )
        self._butKillpacket = Tkinter.Button(self._frame_3,
            text = "kill packet",
        )
        self._butResetsoft = Tkinter.Button(self._frame_3,
            text = "soft reset",
        )

        # widget commands

        self._txLog.configure(
            xscrollcommand = self._txLog_xscrollcommand
        )
        self._txLog.configure(
            yscrollcommand = self._txLog_yscrollcommand
        )
        self._butAdd.configure(
            command = self._butAdd_command
        )
        self._butStart.configure(
            command = self._butStart_command
        )
        self._butExit.configure(
            command = self._butExit_command
        )
        self._butUpdate.configure(
            command = self._butUpdate_command
        )
        self._butHistory.configure(
            command = self._butHistory_command
        )
        self._butPwd.configure(
            command = self._butPwd_command
        )
        self._butKill.configure(
            command = self._butKill_command
        )
        self._butShutdown.configure(
            command = self._butShutdown_command
        )
        self._lsPackets.configure(
            xscrollcommand = self._lsPackets_xscrollcommand
        )
        self._lsPackets.configure(
            yscrollcommand = self._sclPackets.set
        )
        self._sclPackets.configure(
            command = self._sclPackets_command
        )
        self._butKillpacket.configure(
            command = self._butKillpacket_command
        )
        self._butResetsoft.configure(
            command = self._butResetsoft_command
        )


        # Geometry Management
        self._frame_1.grid(
            in_    = root,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_2.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_4.grid(
            in_    = root,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_5.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._labelframe_1.grid(
            in_    = self._frame_1,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 40,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._labelframe_2.grid(
            in_    = self._frame_1,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_3.grid(
            in_    = self._frame_2,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_6.grid(
            in_    = self._frame_2,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._txLog.grid(
            in_    = self._labelframe_2,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._labStatus.grid(
            in_    = self._labelframe_1,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._butAdd.grid(
            in_    = self._frame_3,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butStart.grid(
            in_    = self._frame_3,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butExit.grid(
            in_    = self._frame_4,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._panedwindow_1.grid(
            in_    = self._frame_4,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._butUpdate.grid(
            in_    = self._frame_3,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butHistory.grid(
            in_    = self._frame_3,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butPwd.grid(
            in_    = self._frame_3,
            column = 1,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butKill.grid(
            in_    = self._frame_4,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butShutdown.grid(
            in_    = self._frame_5,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._panedwindow_2.grid(
            in_    = self._frame_5,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._lsPackets.grid(
            in_    = self._frame_6,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._sclPackets.grid(
            in_    = self._frame_6,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ns"
        )
        self._butKillpacket.grid(
            in_    = self._frame_3,
            column = 2,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butResetsoft.grid(
            in_    = self._frame_3,
            column = 2,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 392, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(1, weight = 1, minsize = 298, pad = 0)
        root.grid_columnconfigure(2, weight = 1, minsize = 263, pad = 0)
        self._frame_1.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_1.grid_rowconfigure(2, weight = 1, minsize = 40, pad = 0)
        self._frame_1.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_2.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_2.grid_rowconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_2.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_3.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_3.grid_rowconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_3.grid_rowconfigure(3, weight = 0, minsize = 40, pad = 0)
        self._frame_3.grid_rowconfigure(4, weight = 0, minsize = 40, pad = 0)
        self._frame_3.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_3.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_4.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_4.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_4.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_4.grid_columnconfigure(3, weight = 0, minsize = 40, pad = 0)
        self._frame_5.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_5.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_5.grid_columnconfigure(2, weight = 1, minsize = 40, pad = 0)
        self._frame_6.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_6.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_6.grid_columnconfigure(2, weight = 0, minsize = 33, pad = 0)
        self._labelframe_1.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._labelframe_1.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._labelframe_2.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._labelframe_2.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)


